name: "Github Deployment Action"
description: "Create a GitHub Deployment"
author: "louy"
branding:
  icon: arrow-up
  color: black
inputs:
  initial_status:
    description: "Initial status for the deployment"
    default: "pending"
    required: false
  ref:
    description: "The reference for the deployment"
    required: false
  sha:
    description: "The commit sha for the deployment"
    required: false
  token:
    description: "Github repository token"
    required: true
  target_url:
    description: "Target url location"
    required: false
  description:
    description: "Descriptive message about the deployment"
    required: false
  environment:
    description: "The name of the environment for the deployment"
    default: "production"
    required: false
  transient_environment:
    description: "Whether or not the environment is transient"
    required: false
    default: "false"
  auto_merge:
    description: "Enable auto_merge"
    required: false
    default: "false"
outputs:
  deployment_id:
    description: "The ID of the created deployment"
runs:
  using: "node12"
  main: "dist/index.js"
